version: '3'
services:
  book-service:
    build: ./book-service
    ports:
      - "8081:8081"
    environment:
      - SERVER_PORT=8081
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8081/actuator/health" ]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 10s

  purchase-service:
    build: ./purchase-service
    ports:
      - "8082:8082"
    environment:
      - SERVER_PORT=8082
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8082/actuator/health" ]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 10s

  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    environment:
      - BOOK_SERVICE_URL=http://book-service:8081/graphql
      - PURCHASE_SERVICE_URL=http://purchase-service:8082/graphql
    depends_on:
      book-service:
        condition: service_healthy
      purchase-service:
        condition: service_healthy
